--------------------------------------------------------
--  File created - Saturday-December-03-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BAGAGE
--------------------------------------------------------

  CREATE TABLE "AMIN"."BAGAGE" 
   (	"ID_B" NUMBER(*,0), 
	"NB_B" NUMBER(*,0), 
	"TYPE" VARCHAR2(30 BYTE), 
	"POIDS" FLOAT(126), 
	"DIMENSION" FLOAT(126), 
	"ALERTE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AMIN.BAGAGE
SET DEFINE OFF;
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (5,5,'c',5,5,null);
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (2,8,'accessoire personnel',8,8,null);
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (3,3,'b',3,3,null);
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (12,12,'d',12,12,null);
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (9,9,'z',9,9,null);
Insert into AMIN.BAGAGE (ID_B,NB_B,TYPE,POIDS,DIMENSION,ALERTE) values (222,5,'test',5.6,5.6,null);
--------------------------------------------------------
--  DDL for Index BAGAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMIN"."BAGAGE_PK" ON "AMIN"."BAGAGE" ("ID_B") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BAGAGE
--------------------------------------------------------

  ALTER TABLE "AMIN"."BAGAGE" MODIFY ("NB_B" NOT NULL ENABLE);
  ALTER TABLE "AMIN"."BAGAGE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "AMIN"."BAGAGE" MODIFY ("POIDS" NOT NULL ENABLE);
  ALTER TABLE "AMIN"."BAGAGE" MODIFY ("DIMENSION" NOT NULL ENABLE);
  ALTER TABLE "AMIN"."BAGAGE" ADD CONSTRAINT "BAGAGE_PK" PRIMARY KEY ("ID_B")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
